apiVersion: v1
kind: Service
metadata:
  name: blog-mongo-srv
spec:
  selector:
    app: blog-mongodb
  ports:
    - name: tcp-db
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
