apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-mongodb-sts
  labels:
    env-type: stagedb
    version: v1
spec:
  selector:
    matchLabels:
      app: blog-mongodb
  serviceName: blog-mongo-srv
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-mongodb
    spec:
      serviceAccountName: grpc-blogdb
      containers:
      - name: blog-mongodb
        image: mongo
        imagePullPolicy: Always
        volumeMounts:
        - name: blog-mongo-presistent
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: blog-mongo-presistent
    spec:
      storageClassName: longhorn
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

