apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-mongo-depl
  labels:
    db-type: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-mongo
  template:
    metadata:
      labels:
        app: blog-mongo
    spec:
      containers:
        - name: blog-mongo
          image: mongo
          imagePullPolicy: Always

          
---
apiVersion: v1
kind: Service
metadata:
  name: blog-mongo-srv
spec:
  selector:
    app: blog-mongo
  ports:
    - name: tcp-db
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
