apiVersion: serving.knative.dev/v1
kind: Service 
metadata:
  name: grpc-blog-server
  labels:
    type: stage-depl
    version: v1
spec:
  template:
    spec:
      serviceAccountName: grpc-blogserver
      containers:
        - image: quay.io/narendev/blogserver:v1
          ports:
            - name: h2c
              containerPort: 50051
          env:
            - name: MONGO_DB_URI
              value: "mongodb://blog-mongo-srv:27017/"